import { Container, HostStats, ResourceUsage } from './types';
export const mockContainers: Container[] = [
  {
    id: 'a1b2c3d4e5f6',
    name: 'web-server-prod',
    image: 'nginx:latest',
    status: 'running',
    ports: [{ privatePort: 80, publicPort: 8080, type: 'tcp' }],
    cpuUsage: 15.5,
    memoryUsage: 256,
    memoryLimit: 1024,
    uptime: '3 days',
  },
  {
    id: 'b2c3d4e5f6a1',
    name: 'database-main',
    image: 'postgres:13',
    status: 'running',
    ports: [{ privatePort: 5432, publicPort: 5432, type: 'tcp' }],
    cpuUsage: 45.2,
    memoryUsage: 1024,
    memoryLimit: 4096,
    uptime: '1 week',
  },
  {
    id: 'c3d4e5f6a1b2',
    name: 'redis-cache',
    image: 'redis:6-alpine',
    status: 'running',
    ports: [{ privatePort: 6379, publicPort: 6379, type: 'tcp' }],
    cpuUsage: 5.1,
    memoryUsage: 128,
    memoryLimit: 512,
    uptime: '2 hours',
  },
  {
    id: 'd4e5f6a1b2c3',
    name: 'worker-jobs',
    image: 'ubuntu:20.04',
    status: 'exited',
    ports: [],
    cpuUsage: 0,
    memoryUsage: 0,
    memoryLimit: 2048,
    uptime: 'N/A',
  },
  {
    id: 'e5f6a1b2c3d4',
    name: 'api-gateway',
    image: 'kong:latest',
    status: 'restarting',
    ports: [
      { privatePort: 8000, publicPort: 8000, type: 'tcp' },
      { privatePort: 8443, publicPort: 8443, type: 'tcp' },
    ],
    cpuUsage: 80.0,
    memoryUsage: 512,
    memoryLimit: 1024,
    uptime: '5 minutes',
  },
  {
    id: 'f6a1b2c3d4e5',
    name: 'monitoring-agent',
    image: 'prom/prometheus:v2.26.0',
    status: 'paused',
    ports: [{ privatePort: 9090, publicPort: 9090, type: 'tcp' }],
    cpuUsage: 0.1,
    memoryUsage: 64,
    memoryLimit: 256,
    uptime: '1 day',
  },
];
export const mockHostStats: HostStats = {
  cpuUsage: 35,
  memoryUsage: 8.5,
  memoryTotal: 32,
  diskUsage: 250,
  diskTotal: 1000,
  networkIngress: 12.5,
  networkEgress: 2.1,
};
export const mockResourceUsage: ResourceUsage[] = [
  { time: '10:00', cpu: 20, memory: 30 },
  { time: '10:05', cpu: 25, memory: 32 },
  { time: '10:10', cpu: 22, memory: 35 },
  { time: '10:15', cpu: 30, memory: 40 },
  { time: '10:20', cpu: 35, memory: 38 },
  { time: '10:25', cpu: 40, memory: 45 },
  { time: '10:30', cpu: 38, memory: 42 },
];
export const mockSummary = {
  containers: {
    running: mockContainers.filter(c => c.status === 'running').length,
    total: mockContainers.length,
  },
  images: 25,
  volumes: 12,
  networks: 8,
};